### PR TITLE
take into account local culture settings for timestamps and parsing

### PR DESCRIPTION
**Pull request by ghost**
doubles

## Description

The converter was failing when parsing auto-save files generated in European culture.  Take that into account when parsing timestamps and doubles.

Fixes # (issue)

### Type of change

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Ran the converter on a sample file provided by a customer.

### Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have done tests that prove my fix is effective or that my feature works and described them in 'How has this been tested?'

### CODE REVIEW

**Comment by AhNesh** [comment]
In Soundcheck, is it possible to set the output format for numbers and dates? If that is possible, I think a better solution would be to require it to be set to the format that the converter supports. 

What if Soundcheck and WATS Client isn't installed on the same computer and have different CurrentUICulture? It is not uncommon for WATS Client to read import files from a shared folder that other machines put files into.

If that is not possible, I would add a cultureCode parameter to the converter and use that culture, so the converter isn't relying on how the computer is set up. This way it is fully configurable for the user, and if they need multiple cultures they can install the converter multiple times with a different cultureCode.

And I would do the same for dates, add a dateFormat parameter to the converter, then use that to parse the date, instead of trying and failing.

What do you think about that?

BTW, this is the kind of discussion that is nice to do in an issue before implementing the solution.

**Comment by ghost** [comment]
Anders,

No, it's not possible to set the output format for numbers and dates from
within SoundCheck.

Apparently, there is already a culture code parameter for the converter.
Is it not being used by the converter?  I think that's all we would need vs
two parameters, one for numbers and another for dates.

-- Rick

**Comment by AhNesh** [comment]
Hi,

I have added a cultureCode parameter which by default is en-US. The culture is used to parse numbers and dates. Could you also check that this works?

The converter didn't actually accept custom parameters, there was no way to input them, so I added that too.

I also separated the example files into US and EU so it is easier to tell them apart.

**Comment by ghost** [comment]
Changes look good and have been validated.  GTG

**Review by AhNesh — APPROVED** [review]

**Pull request merged**
